export const drivers = [
  'Andi3810', 'Evil Tactician', 'hxrry27', 'Jober', 'Kesla', 'Kol_ri', 'Kyuubi0kid', 'LFFPicard', 
  'MagicallyMichael', 'SeerUK', 'Spacey', 'Thorston', 'Timmeh1090', 'Totsuka', 'Xerxes'
];

export const teams = [
  'Williams', 'Renault', 'McLaren', 'Haas', 'Alfa Romeo', 'Alpha Tauri', 'Aston Martin',
  'Alpine', 'Mercedes', 'Ferrari', 'Red Bull', 'Racing Point', 'Toro Rosso'
];

export const trackData = {
  bahrain: { country: 'BAHRAIN', name: 'Bahrain International Circuit', length: 5.412, turns: 15, firstGrandPrix: 2004, laps: 57 },
  jeddah: { country: 'SAUDI ARABIA', name: 'Jeddah Corniche Circuit', length: 6.174, turns: 27, firstGrandPrix: 2021, laps: 50 },
  melbourne: { country: 'AUSTRALIA', name: 'Albert Park Circuit', length: 5.278, turns: 14, firstGrandPrix: 1996, laps: 58 },
  baku: { country: 'AZERBAIJAN', name: 'Baku City Circuit', length: 6.003, turns: 20, firstGrandPrix: 2016, laps: 51 },
  miami: { country: 'MIAMI', name: 'Miami International Autodrome', length: 5.412, turns: 19, firstGrandPrix: 2022, laps: 57 },
  imola: { country: 'EMILIA-ROMAGNA', name: 'Imola', length: 4.909, turns: 19, firstGrandPrix: 1980, laps: 63 },
  monaco: { country: 'MONACO', name: 'Circuit de Monaco', length: 3.337, turns: 19, firstGrandPrix: 1950, laps: 78 },
  barcelona: { country: 'SPAIN', name: 'Circuit de Barcelona-Catalunya', length: 4.657, turns: 14, firstGrandPrix: 1991, laps: 66 },
  montreal: { country: 'CANADA', name: 'Circuit Gilles Villeneuve', length: 4.361, turns: 14, firstGrandPrix: 1978, laps: 70 },
  spielberg: { country: 'AUSTRIA', name: 'Red Bull Ring', length: 4.318, turns: 10, firstGrandPrix: 1970, laps: 71 },
  silverstone: { country: 'GREAT BRITAIN', name: 'Silverstone', length: 5.891, turns: 18, firstGrandPrix: 1950, laps: 52 },
  hungaroring: { country: 'HUNGARY', name: 'Hungaroring', length: 4.381, turns: 14, firstGrandPrix: 1986, laps: 70 },
  'spa-francorchamps': { country: 'BELGIUM', name: 'Circuit de Spa-Francorchamps', length: 7.004, turns: 19, firstGrandPrix: 1950, laps: 44 },
  zandvoort: { country: 'NETHERLANDS', name: 'Circuit Zandvoort', length: 4.259, turns: 14, firstGrandPrix: 1952, laps: 72 },
  monza: { country: 'ITALY', name: 'Monza', length: 5.793, turns: 11, firstGrandPrix: 1950, laps: 53 },
  singapore: { country: 'SINGAPORE', name: 'Marina Bay Street Circuit', length: 4.94, turns: 19, firstGrandPrix: 2008, laps: 62 },
  suzuka: { country: 'JAPAN', name: 'Suzuka', length: 5.807, turns: 18, firstGrandPrix: 1987, laps: 53 },
  losail: { country: 'QATAR', name: 'Lusail International Circuit', length: 5.419, turns: 16, firstGrandPrix: 2021, laps: 57 },
  austin: { country: 'AUSTIN', name: 'Circuit of the Americas', length: 5.513, turns: 20, firstGrandPrix: 2012, laps: 56 },
  mexico: { country: 'MEXICO', name: 'Autódromo Hermanos Rodríguez', length: 4.304, turns: 17, firstGrandPrix: 1963, laps: 71 },
  interlagos: { country: 'BRAZIL', name: 'Interlagos', length: 4.309, turns: 15, firstGrandPrix: 1973, laps: 71 },
  'las-vegas': { country: 'LAS VEGAS', name: 'Las Vegas Street Circuit', length: 6.201, turns: 17, firstGrandPrix: 2023, laps: 50 },
  'yas-marina': { country: 'ABU DHABI', name: 'Yas Marina Circuit', length: 5.281, turns: 16, firstGrandPrix: 2009, laps: 58 },
  portimao: { country: 'PORTUGAL', name: 'Algarve International Circuit', length: 4.653, turns: 15, firstGrandPrix: 2020, laps: 66 },
  'paul-ricard': { country: 'FRANCE', name: 'Paul Ricard', length: 5.842, turns: 15, firstGrandPrix: 1971, laps: 53 },
  shanghai: { country: 'CHINA', name: 'Shanghai International Circuit', length: 5.451, turns: 16, firstGrandPrix: 2004, laps: 56 },
  russia: { country: 'RUSSIA', name: 'Sochi Autodrom', length: 5.848, turns: 18, firstGrandPrix: 2014, laps: 53 },
};

const normalizeRaceName = (name) => name.toLowerCase().replace(/\s+/g, '-');

export const seasons = {
  1: {
    game: '',
    dates: '',
    lineups: {
      'Andi3810': 'Alfa Romeo',
      'Evil Tactician': 'McLaren',
      'Kol_ri': 'Haas',
      'Kyuubi0kid': 'Renault',
      'LFFPicard': 'Haas',
      'MagicallyMichael': 'Renault',
      'Spacey': 'Ferrari',
      'Thorston': 'McLaren',
    },
    races: {
      'bahrain': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'jeddah': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'melbourne': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'baku': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'miami': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'imola': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'monaco': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'barcelona': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'montreal': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'spielberg': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'silverstone': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'hungaroring': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'spa-francorchamps': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'zandvoort': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'monza': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'singapore': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'suzuka': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'losail': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'austin': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'mexico': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'interlagos': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'las-vegas': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'yas-marina': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'portimao': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'paul-ricard': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'shanghai': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'russia': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null }
    }
  },
  2: {
    game: 'F1 2019',
    dates: 'Unavailable',
    lineups: {
      'MagicallyMichael': 'McLaren',
      'Evil Tactician': 'Haas', 
      'LFFPicard': 'Racing Point', 
      'Kol_ri': 'Alfa Romeo', 
      'Jober': 'Renault',
      'Kyuubi0kid': 'Mercedes',
      'Spacey': 'Ferrari',
      'Andi3810': 'Toro Rosso',
      'Vettel': 'Ferrari',
      'Bottas': 'Mercedes',
      'Verstappen': 'Red Bull',
      'Perez': 'Racing Point',
      'Norris': 'McLaren',
      'Gasly': 'Toro Rosso',
      'Grosjean': 'Haas',
      'Raikkonen': 'Alfa Romeo',
      'Ricciardo': 'Renault',
      'Albon': 'Red Bull',
      'Russell': 'Williams',
      'Kubica': 'Williams'
    },
    races: {
      'bahrain': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'jeddah': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'melbourne': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'baku': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'miami': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'imola': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'monaco': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'barcelona': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'montreal': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'spielberg': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'silverstone': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'hungaroring': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'spa-francorchamps': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'zandvoort': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'monza': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'singapore': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'suzuka': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'losail': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'austin': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'mexico': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'interlagos': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'las-vegas': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'yas-marina': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'portimao': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'paul-ricard': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'shanghai': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'russia': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null }
    },
    standings: {
      drivers: [
        { position: 'P1', driver: 'Andi3810', points: 381, team: 'Toro Rosso' },
        { position: 'P2', driver: 'MagicallyMichael', points: 276, team: 'McLaren' },
        { position: 'P3', driver: 'Evil Tactician', points: 274, team: 'Haas' },
        { position: 'P4', driver: 'Kol_ri', points: 252, team: 'Alfa Romeo' },
        { position: 'P5', driver: 'LFFPicard', points: 197, team: 'Racing Point' },
        { position: 'P6', driver: 'Kyuubi0kid', points: 153, team: 'Mercedes' },
        { position: 'P7', driver: 'Vettel', points: 111, team: 'Ferrari' },
        { position: 'P8', driver: 'Spacey', points: 87, team: 'Ferrari' },
        { position: 'P9', driver: 'Bottas', points: 84, team: 'Mercedes' },
        { position: 'P10', driver: 'Verstappen', points: 76, team: 'Red Bull' },
        { position: 'P11', driver: 'Jober', points: 64, team: 'Renault' },
        { position: 'P12', driver: 'Perez', points: 41, team: 'Racing Point' },
        { position: 'P13', driver: 'Norris', points: 35, team: 'McLaren' },
        { position: 'P14', driver: 'Gasly', points: 20, team: 'Toro Rosso' },
        { position: 'P15', driver: 'Grosjean', points: 11, team: 'Haas' },
        { position: 'P16', driver: 'Raikkonen', points: 7, team: 'Alfa Romeo' },
        { position: 'P17', driver: 'Ricciardo', points: 4, team: 'Renault' },
        { position: 'P18', driver: 'Albon', points: 2, team: 'Red Bull' },
        { position: 'P19', driver: 'Russell', points: 1, team: 'Williams' },
        { position: 'P20', driver: 'Kubica', points: 0, team: 'Williams' }
      ],
      constructors: [
        { position: 'P1', constructor: 'Toro Rosso', points: 401 },
        { position: 'P2', constructor: 'McLaren', points: 311 },
        { position: 'P3', constructor: 'Haas', points: 285 },
        { position: 'P4', constructor: 'Alfa Romeo', points: 259 },
        { position: 'P5', constructor: 'Racing Point', points: 238 },
        { position: 'P6', constructor: 'Mercedes', points: 237 },
        { position: 'P7', constructor: 'Ferrari', points: 198 },
        { position: 'P8', constructor: 'Red Bull', points: 78 },
        { position: 'P9', constructor: 'Renault', points: 68 },
        { position: 'P10', constructor: 'Williams', points: 1 }
      ]
    }
  },
  3: {
    game: 'F1 2020',
    dates: 'March 21 > Aug 21',
    lineups: {
      'MagicallyMichael': 'Haas',
      'Evil Tactician': 'Renault',
      'LFFPicard': 'Renault',
      'Kol_ri': 'Williams',
      'Jober': 'McLaren', 
      'Spacey': 'McLaren', 
      'Kyuubi0kid': 'Ferrari',
      'Andi3810': 'Williams',
      'Hamilton': 'Mercedes',
      'Verstappen': 'Red Bull',
      'Bottas': 'Mercedes',
      'Albon': 'Red Bull',
      'Perez': 'Racing Point',
      'Leclerc': 'Ferrari',
      'Stroll': 'Racing Point',
      'Gasly': 'Alpha Tauri',
      'Giovinazzi': 'Alfa Romeo',
      'Kvyat': 'Alpha Tauri',
      'Raikkonen': 'Alfa Romeo',
      'Grosjean': 'Haas'
    },
    races: {
      'bahrain': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'jeddah': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'melbourne': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'baku': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'miami': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'imola': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'monaco': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'barcelona': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'montreal': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'spielberg': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'silverstone': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'hungaroring': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'spa-francorchamps': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'zandvoort': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'monza': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'singapore': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'suzuka': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'losail': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'austin': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'mexico': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'interlagos': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'las-vegas': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'yas-marina': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'portimao': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'paul-ricard': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'shanghai': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'russia': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null }
    },
    standings: {
      drivers: [
        { position: 'P1', driver: 'Andi3810', points: 405, team: 'Williams' },
        { position: 'P2', driver: 'LFFPicard', points: 322, team: 'Renault' },
        { position: 'P3', driver: 'Evil Tactician', points: 321, team: 'Renault' },
        { position: 'P4', driver: 'Kol_ri', points: 210, team: 'Williams' },
        { position: 'P5', driver: 'MagicallyMichael', points: 189, team: 'Haas' },
        { position: 'P6', driver: 'Hamilton', points: 168, team: 'Mercedes' },
        { position: 'P7', driver: 'Verstappen', points: 148, team: 'Red Bull' },
        { position: 'P8', driver: 'Bottas', points: 108, team: 'Merc' },
        { position: 'P9', driver: 'Kyuubi0kid', points: 98, team: 'Ferrari' },
        { position: 'P10', driver: 'Albon', points: 80, team: 'Red Bull' },
        { position: 'P11', driver: 'Perez', points: 50, team: 'Racing Point' },
        { position: 'P12', driver: 'Jober', points: 32, team: 'McLaren' },
        { position: 'P13', driver: 'Leclerc', points: 31, team: 'Ferrari' },
        { position: 'P14', driver: 'Spacey', points: 25, team: 'McLaren' },
        { position: 'P15', driver: 'Stroll', points: 21, team: 'Racing Point' },
        { position: 'P16', driver: 'Gasly', points: 19, team: 'Alpha Tauri' },
        { position: 'P17', driver: 'Giovinazzi', points: 8, team: 'Alfa Romeo' },
        { position: 'P18', driver: 'Kvyat', points: 8, team: 'Alpha Tauri' },
        { position: 'P19', driver: 'Raikkonen', points: 0, team: 'Alfa Romeo' },
        { position: 'P20', driver: 'Grosjean', points: 0, team: 'Haas' }
      ],
      constructors: [
        { position: 'P1', constructor: 'Renault', points: 643 },
        { position: 'P2', constructor: 'Williams', points: 615 },
        { position: 'P3', constructor: 'Mercedes', points: 276 },
        { position: 'P4', constructor: 'Red Bull', points: 228 },
        { position: 'P5', constructor: 'Haas', points: 189 },
        { position: 'P6', constructor: 'Ferrari', points: 129 },
        { position: 'P7', constructor: 'Racing Point', points: 71 },
        { position: 'P8', constructor: 'McLaren', points: 57 },
        { position: 'P9', constructor: 'Alpha Tauri', points: 27 },
        { position: 'P10', constructor: 'Alfa Romeo', points: 8 }
      ]
    }
  },
  4: {
    game: 'F1 2020',
    dates: 'Aug 21 > Jan 22',
    lineups: {
      'hxrry27': 'Alfa Romeo',
      'MagicallyMichael': 'Alpha Tauri',
      'Evil Tactician': 'McLaren',
      'LFFPicard': 'McLaren',
      'Kol_ri': 'Alfa Romeo',
      'Jober': 'Racing Point',
      'Spacey': 'Ferrari',
      'Kyuubi0kid': 'Racing Point',
      'Andi3810': 'Williams',
      'Hamilton': 'Mercedes',
      'Verstappen': 'Red Bull',
      'Bottas': 'Mercedes',
      'Albon': 'Red Bull',
      'Perez': 'Racing Point',
      'Ricciardo': 'Renault',
      'Ocon': 'Renault',
      'Leclerc': 'Ferrari',
      'Gasly': 'Alpha Tauri',
      'Magnussen': 'Haas',
      'Grosjean': 'Haas',
      'Latifi': 'Williams'
    },
    races: {
      'bahrain': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'jeddah': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'melbourne': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'baku': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'imola': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'monaco': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'barcelona': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'montreal': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'spielberg': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'silverstone': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'hungaroring': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'spa-francorchamps': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'zandvoort': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'monza': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'singapore': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'suzuka': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'austin': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'mexico': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'interlagos': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'yas-marina': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'portimao': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'paul-ricard': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'shanghai': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'russia': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null }
    },
    standings: {
      drivers: [
        { position: 'P1', driver: 'Evil Tactician', points: 383, team: 'McLaren' },
        { position: 'P2', driver: 'LFFPicard', points: 357, team: 'McLaren' },
        { position: 'P3', driver: 'MagicallyMichael', points: 291, team: 'Alpha Tauri' },
        { position: 'P4', driver: 'hxrry27', points: 245, team: 'Alfa Romeo' },
        { position: 'P5', driver: 'Kyuubi0kid', points: 178, team: 'Racing Point' },
        { position: 'P6', driver: 'Kol_ri', points: 164, team: 'Alfa Romeo' },
        { position: 'P7', driver: 'Hamilton', points: 134, team: 'Mercedes' },
        { position: 'P8', driver: 'Jober', points: 99, team: 'Racing Point' },
        { position: 'P9', driver: 'Verstappen', points: 90, team: 'Red Bull' },
        { position: 'P10', driver: 'Andi3810', points: 75, team: 'Williams' },
        { position: 'P11', driver: 'Bottas', points: 73, team: 'Mercedes' },
        { position: 'P12', driver: 'Albon', points: 50, team: 'Red Bull' },
        { position: 'P13', driver: 'Ricciardo', points: 31, team: 'Renault' },
        { position: 'P14', driver: 'Ocon', points: 25, team: 'Renault' },
        { position: 'P15', driver: 'Leclerc', points: 24, team: 'Ferrari' },
        { position: 'P16', driver: 'Spacey', points: 10, team: 'Ferrari' },
        { position: 'P17', driver: 'Gasly', points: 6, team: 'Alpha Tauri' },
        { position: 'P18', driver: 'Magnussen', points: 4, team: 'Haas' },
        { position: 'P19', driver: 'Grosjean', points: 2, team: 'Haas' },
        { position: 'P20', driver: 'Latifi', points: 0, team: 'Williams' }
      ],
      constructors: [
        { position: 'P1', constructor: 'McLaren', points: 740 },
        { position: 'P2', constructor: 'Alfa Romeo', points: 409 },
        { position: 'P3', constructor: 'Alpha Tauri', points: 297 },
        { position: 'P4', constructor: 'Racing Point', points: 277 },
        { position: 'P5', constructor: 'Mercedes', points: 207 },
        { position: 'P6', constructor: 'Red Bull', points: 140 },
        { position: 'P7', constructor: 'Williams', points: 75 },
        { position: 'P8', constructor: 'Renault', points: 56 },
        { position: 'P9', constructor: 'Ferrari', points: 34 },
        { position: 'P10', constructor: 'Haas', points: 6 }
      ]
    }
  },
  5: {
    game: 'F1 2021',
    dates: 'Jan 22 > Jun 22',
    lineups: {
      'hxrry27': 'Aston Martin',
      'MagicallyMichael': 'Alpine',
      'Evil Tactician': 'Alpha Tauri',
      'LFFPicard': 'Alpha Tauri',
      'Kol_ri': 'Alpine',
      'Jober': 'McLaren',
      'Spacey': 'Ferrari',
      'Kyuubi0kid': 'Ferrari',
      'Timmeh1090': 'Alfa Romeo',
      'Andi3810': 'Alfa Romeo',
      'Verstappen': 'Red Bull',
      'Hamilton': 'Mercedes',
      'Bottas': 'Mercedes',
      'Perez': 'Red Bull',
      'Norris': 'McLaren',
      'Vettel': 'Aston Martin',
      'Russell': 'Williams',
      'Latifi': 'Williams',
      'Schumacher': 'Haas',
      'Mazepin': 'Haas'
    },
    races: {
      'bahrain': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'jeddah': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'melbourne': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'baku': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'imola': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'monaco': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'barcelona': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'montreal': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'spielberg': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.14.940', podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'silverstone': { fastestLapDriver: 'Kol_ri', fastestLapTime: '1.31.632', podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'hungaroring': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.21.078', podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'spa-francorchamps': { fastestLapDriver: 'MagicallyMichael', fastestLapTime: '1.47.394', podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'zandvoort': { fastestLapDriver: 'MagicallyMichael', fastestLapTime: '1.14.636', podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'monza': { fastestLapDriver: 'Kol_ri', fastestLapTime: '1.24.925', podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'singapore': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.43.288', podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'suzuka': { fastestLapDriver: 'Kol_ri', fastestLapTime: '1.33.157', podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'austin': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.36.666', podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'mexico': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.18.752', podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'interlagos': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.10.443', podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'yas-marina': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.40.659', podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'portimao': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'paul-ricard': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'shanghai': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null },
      'russia': { fastestLapDriver: null, fastestLapTime: null, podium1: null, podium2: null, podium3: null, poleDriver: null, poleTime: null }
    },
    standings: {
      drivers: [
        { position: 'P1', driver: 'hxrry27', points: 332, team: 'Aston Martin' },
        { position: 'P2', driver: 'Verstappen', points: 226, team: 'Red Bull' },
        { position: 'P3', driver: 'Hamilton', points: 219, team: 'Mercedes' },
        { position: 'P4', driver: 'MagicallyMichael', points: 203, team: 'Alpine' },
        { position: 'P5', driver: 'Bottas', points: 202, team: 'Mercedes' },
        { position: 'P6', driver: 'Evil Tactician', points: 198, team: 'Alpha Tauri' },
        { position: 'P7', driver: 'LFFPicard', points: 153, team: 'Alpha Tauri' },
        { position: 'P8', driver: 'Perez', points: 152, team: 'Red Bull' },
        { position: 'P9', driver: 'Kol_ri', points: 150, team: 'Alpine' },
        { position: 'P10', driver: 'Norris', points: 147, team: 'McLaren' },
        { position: 'P11', driver: 'Kyuubi0kid', points: 99, team: 'Ferrari' },
        { position: 'P12', driver: 'Timmeh1090', points: 85, team: 'Alfa Romeo' },
        { position: 'P13', driver: 'Vettel', points: 81, team: 'Aston Martin' },
        { position: 'P14', driver: 'Russell', points: 54, team: 'Williams' },
        { position: 'P15', driver: 'Latifi', points: 53, team: 'Williams' },
        { position: 'P16', driver: 'Andi3810', points: 25, team: 'Alfa Romeo' },
        { position: 'P17', driver: 'Schumacher', points: 21, team: 'Haas' },
        { position: 'P18', driver: 'Spacey', points: 19, team: 'Ferrari' },
        { position: 'P19', driver: 'Mazepin', points: 15, team: 'Haas' },
        { position: 'P20', driver: 'Jober', points: 3, team: 'McLaren' }
      ],
      constructors: [
        { position: 'P1', constructor: 'Mercedes', points: 421 },
        { position: 'P2', constructor: 'Aston Martin', points: 413 },
        { position: 'P3', constructor: 'Red Bull', points: 378 },
        { position: 'P4', constructor: 'Alpine', points: 353 },
        { position: 'P5', constructor: 'Alpha Tauri', points: 351 },
        { position: 'P6', constructor: 'McLaren', points: 150 },
        { position: 'P7', constructor: 'Ferrari', points: 118 },
        { position: 'P8', constructor: 'Alfa Romeo', points: 110 },
        { position: 'P9', constructor: 'Williams', points: 107 },
        { position: 'P10', constructor: 'Haas', points: 36 }
      ]
    }
  },
  6: {
    game: 'F1 2021',
    dates: 'Jun 22 > Dec 22',
    lineups: {
      'hxrry27': 'Alfa Romeo',
      'MagicallyMichael': 'Alfa Romeo',
      'Evil Tactician': 'Alpha Tauri',
      'LFFPicard': 'Aston Martin',
      'Kol_ri': 'Aston Martin',
      'Spacey': 'Ferrari',
      'SeerUK': 'Haas',
      'Kyuubi0kid': 'Alpha Tauri',
      'Timmeh1090': 'Haas',
      'Verstappen': 'Red Bull',
      'Hamilton': 'Mercedes',
      'Perez': 'Red Bull',
      'Bottas': 'Mercedes',
      'Ricciardo': 'McLaren',
      'Norris': 'McLaren',
      'Alonso': 'Alpine',
      'Sainz': 'Ferrari',
      'Ocon': 'Alpine',
      'Russell': 'Williams',
      'Schumacher': 'Haas',
      'Latifi': 'Williams',
      'Tsunoda': 'Alpha Tauri',
      'Gasly': 'Alpha Tauri'
    },
    races: {
      'bahrain': { fastestLapDriver: null, fastestLapTime: null, podium1: 'Evil Tactician', podium2: 'MagicallyMichael', podium3: 'hxrry27', poleDriver: 'Kol_ri', poleTime: '1.29.334' },
      'jeddah': { fastestLapDriver: 'Kol_ri', fastestLapTime: '1.34.045', podium1: 'Kol_ri', podium2: 'hxrry27', podium3: 'Hamilton', poleDriver: 'hxrry27', poleTime: '1.30.868' },
      'melbourne': { fastestLapDriver: 'Hamilton', fastestLapTime: '1.26.450', podium1: 'Verstappen', podium2: 'hxrry27', podium3: 'Kol_ri', poleDriver: 'Kol_ri', poleTime: '1.24.850' },
      'baku': { fastestLapDriver: null, fastestLapTime: null, podium1: 'hxrry27', podium2: 'Evil Tactician', podium3: 'Kol_ri', poleDriver: 'MagicallyMichael', poleTime: null },
      'imola': { fastestLapDriver: null, fastestLapTime: null, podium1: 'hxrry27', podium2: 'MagicallyMichael', podium3: 'Evil Tactician', poleDriver: 'hxrry27', poleTime: '1.17.219' },
      'monaco': { fastestLapDriver: null, fastestLapTime: null, podium1: 'MagicallyMichael', podium2: 'Sainz', podium3: 'Tsunoda', poleDriver: 'Kol_ri', poleTime: '1.12.003' },
      'barcelona': { fastestLapDriver: null, fastestLapTime: null, podium1: 'Verstappen', podium2: 'Evil Tactician', podium3: 'hxrry27', poleDriver: 'hxrry27', poleTime: null },
      'montreal': { fastestLapDriver: null, fastestLapTime: null, podium1: 'hxrry27', podium2: 'Kol_ri', podium3: 'Kyuubi0kid', poleDriver: 'hxrry27', poleTime: '1.11.357' },
      'spielberg': { fastestLapDriver: null, fastestLapTime: null, podium1: 'Evil Tactician', podium2: 'hxrry27', podium3: 'MagicallyMichael', poleDriver: 'Evil Tactician', poleTime: null },
      'silverstone': { fastestLapDriver: null, fastestLapTime: null, podium1: 'Evil Tactician', podium2: 'Kol_ri', podium3: 'MagicallyMichael', poleDriver: null, poleTime: null },
      'hungaroring': { fastestLapDriver: null, fastestLapTime: null, podium1: 'Kyuubi0kid', podium2: 'hxrry27', podium3: 'Gasly', poleDriver: null, poleTime: null },
      'spa-francorchamps': { fastestLapDriver: null, fastestLapTime: null, podium1: 'hxrry27', podium2: 'Kyuubi0kid', podium3: 'Verstappen', poleDriver: 'Kyuubi0kid', poleTime: '1.45.816' },
      'zandvoort': { fastestLapDriver: null, fastestLapTime: null, podium1: 'hxrry27', podium2: 'Evil Tactician', podium3: 'LFFPicard', poleDriver: 'hxrry27', poleTime: '1.24.584' },
      'monza': { fastestLapDriver: null, fastestLapTime: null, podium1: 'Evil Tactician', podium2: 'hxrry27', podium3: 'Kol_ri', poleDriver: 'Evil Tactician', poleTime: null },
      'singapore': { fastestLapDriver: null, fastestLapTime: null, podium1: 'Evil Tactician', podium2: 'MagicallyMichael', podium3: 'LFFPicard', poleDriver: 'Evil Tactician', poleTime: '2.00.554' },
      'suzuka': { fastestLapDriver: null, fastestLapTime: null, podium1: 'Evil Tactician', podium2: 'hxrry27', podium3: 'Kyuubi0kid', poleDriver: 'Evil Tactician', poleTime: '1.32.102' },
      'austin': { fastestLapDriver: null, fastestLapTime: null, podium1: 'hxrry27', podium2: 'Evil Tactician', podium3: 'Verstappen', poleDriver: 'hxrry27', poleTime: '1.35.347' },
      'mexico': { fastestLapDriver: null, fastestLapTime: null, podium1: 'Evil Tactician', podium2: 'hxrry27', podium3: 'Kyuubi0kid', poleDriver: 'Evil Tactician', poleTime: '1.17.240' },
      'interlagos': { fastestLapDriver: null, fastestLapTime: null, podium1: 'hxrry27', podium2: 'Evil Tactician', podium3: 'Kyuubi0kid', poleDriver: 'Evil Tactician', poleTime: '1.08.896' },
      'yas-marina': { fastestLapDriver: null, fastestLapTime: null, podium1: 'hxrry27', podium2: 'Kol_ri', podium3: 'MagicallyMichael', poleDriver: 'hxrry27', poleTime: '1.38.159' },
      'portimao': { fastestLapDriver: null, fastestLapTime: null, podium1: 'hxrry27', podium2: 'Evil Tactician', podium3: 'Kyuubi0kid', poleDriver: 'Evil Tactician', poleTime: '1.19.102' },
      'paul-ricard': { fastestLapDriver: null, fastestLapTime: null, podium1: 'Evil Tactician', podium2: 'Kyuubi0kid', podium3: 'Kol_ri', poleDriver: 'Kol_ri', poleTime: '1.32.118' },
      'shanghai': { fastestLapDriver: null, fastestLapTime: null, podium1: 'hxrry27', podium2: 'Verstappen', podium3: 'Perez', poleDriver: 'MagicallyMichael', poleTime: '1.34.820' },
      'russia': { fastestLapDriver: null, fastestLapTime: null, podium1: 'Evil Tactician', podium2: 'hxrry27', podium3: 'Kyuubi0kid', poleDriver: 'Kyuubi0kid', poleTime: '1.33.917' }
    },
    standings: {
      drivers: [
        { position: 'P1', driver: 'hxrry27', points: 285, team: 'Alfa Romeo' },
        { position: 'P2', driver: 'LFFPicard', points: 273, team: 'Aston Martin' },
        { position: 'P3', driver: 'Verstappen', points: 266, team: 'Red Bull' },
        { position: 'P4', driver: 'Hamilton', points: 259, team: 'Mercedes' },
        { position: 'P5', driver: 'Kol_ri', points: 229, team: 'Aston Martin' },
        { position: 'P6', driver: 'Perez', points: 209, team: 'Red Bull' },
        { position: 'P7', driver: 'Evil Tactician', points: 162, team: 'Alpha Tauri' },
        { position: 'P8', driver: 'Bottas', points: 144, team: 'Mercedes' },
        { position: 'P9', driver: 'MagicallyMichael', points: 128, team: 'Alfa Romeo' },
        { position: 'P10', driver: 'Kyuubi0kid', points: 125, team: 'Alpha Tauri' },
        { position: 'P11', driver: 'Ricciardo', points: 83, team: 'McLaren' },
        { position: 'P12', driver: 'Norris', points: 77, team: 'McLaren' },
        { position: 'P13', driver: 'Alonso', points: 76, team: 'Alpine' },
        { position: 'P14', driver: 'Sainz', points: 60, team: 'Ferrari' },
        { position: 'P15', driver: 'Ocon', points: 48, team: 'Alpine' },
        { position: 'P16', driver: 'Russell', points: 16, team: 'Williams' },
        { position: 'P17', driver: 'Schumacher', points: 1, team: 'Haas' },
        { position: 'P18', driver: 'Latifi', points: 1, team: 'Williams' },
        { position: 'P19', driver: 'Spacey', points: 0, team: 'Ferrari' },
        { position: 'P20', driver: 'Timmeh1090', points: 0, team: 'Haas' }
      ],
      constructors: [
        { position: 'P1', constructor: 'Aston Martin', points: 502 },
        { position: 'P2', constructor: 'Red Bull', points: 475 },
        { position: 'P3', constructor: 'Alfa Romeo', points: 413 },
        { position: 'P4', constructor: 'Mercedes', points: 403 },
        { position: 'P5', constructor: 'Alpha Tauri', points: 287 },
        { position: 'P6', constructor: 'McLaren', points: 160 },
        { position: 'P7', constructor: 'Alpine', points: 124 },
        { position: 'P8', constructor: 'Ferrari', points: 60 },
        { position: 'P9', constructor: 'Williams', points: 17 },
        { position: 'P10', constructor: 'Haas', points: 1 }
      ]
    }
  },
  7: {
    game: 'F1 2021',
    dates: 'Jan 23 > Jun 23',
    lineups: {
      'hxrry27': 'Alfa Romeo',
      'MagicallyMichael': 'Alfa Romeo',
      'Evil Tactician': 'McLaren',
      'LFFPicard': 'Aston Martin/Haas',
      'Kol_ri': 'Alpine',
      'Jober': 'Mercedes',
      'Spacey': 'Mercedes',
      'Kyuubi0kid': 'McLaren',
      'Verstappen': 'Red Bull',
      'Leclerc': 'Ferrari',
      'Tsunoda': 'Alpha Tauri',
      'Sainz': 'Ferrari',
      'Vettel': 'Aston Martin',
      'Gasly': 'Alpha Tauri',
      'Perez': 'Red Bull',
      'Ocon': 'Alpine',
      'Stroll': 'Aston Martin',
      'Latifi': 'Williams',
      'Russell': 'Williams',
      'Schumacher': 'Haas'
    },
    races: {
      'bahrain': { fastestLapDriver: 'Kol_ri', fastestLapTime: '1.32.640', podium1: 'Evil Tactician', podium2: 'MagicallyMichael', podium3: 'hxrry27', poleDriver: 'Kol_ri', poleTime: '1.29.334' },
      'jeddah': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.32.160', podium1: 'hxrry27', podium2: 'Kol_ri', podium3: 'MagicallyMichael', poleDriver: 'hxrry27', poleTime: '1.30.168' },
      'melbourne': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.26.257', podium1: 'Verstappen', podium2: 'Perez', podium3: 'Evil Tactician', poleDriver: 'hxrry27', poleTime: '1.24.704' },
      'baku': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.44.785', podium1: 'hxrry27', podium2: 'Evil Tactician', podium3: 'Kol_ri', poleDriver: 'MagicallyMichael', poleTime: null },
      'imola': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.19.148', podium1: 'hxrry27', podium2: 'MagicallyMichael', podium3: 'Evil Tactician', poleDriver: 'hxrry27', poleTime: '1.17.219' },
      'monaco': { fastestLapDriver: 'Kol_ri', fastestLapTime: '1.14.681', podium1: 'MagicallyMichael', podium2: 'Sainz', podium3: 'Tsunoda', poleDriver: 'Kol_ri', poleTime: '1.12.003' },
      'barcelona': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.21.356', podium1: 'Verstappen', podium2: 'Evil Tactician', podium3: 'hxrry27', poleDriver: 'hxrry27', poleTime: null },
      'montreal': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.12.703', podium1: 'hxrry27', podium2: 'Kol_ri', podium3: 'Kyuubi0kid', poleDriver: 'hxrry27', poleTime: '1.11.357' },
      'spielberg': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.07.023', podium1: 'Evil Tactician', podium2: 'hxrry27', podium3: 'MagicallyMichael', poleDriver: 'Evil Tactician', poleTime: null },
      'silverstone': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.31.111', podium1: 'Evil Tactician', podium2: 'Kol_ri', podium3: 'MagicallyMichael', poleDriver: 'LFFPicard', poleTime: '1.29.799' },
      'hungaroring': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.33.819', podium1: 'Kyuubi0kid', podium2: 'hxrry27', podium3: 'Gasly', poleDriver: 'LFFPicard', poleTime: '1.18.353' },
      'spa-francorchamps': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.47.110', podium1: 'hxrry27', podium2: 'Kyuubi0kid', podium3: 'Verstappen', poleDriver: 'Kyuubi0kid', poleTime: '1.45.816' },
      'zandvoort': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.15.989', podium1: 'hxrry27', podium2: 'Evil Tactician', podium3: 'LFFPicard', poleDriver: 'hxrry27', poleTime: '1.24.584' },
      'monza': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.24.083', podium1: 'Evil Tactician', podium2: 'hxrry27', podium3: 'Kol_ri', poleDriver: 'Evil Tactician', poleTime: null },
      'singapore': { fastestLapDriver: 'Kol_ri', fastestLapTime: '1.43.374', podium1: 'Evil Tactician', podium2: 'MagicallyMichael', podium3: 'LFFPicard', poleDriver: 'Evil Tactician', poleTime: '2.00.554' },
      'suzuka': { fastestLapDriver: 'Jober', fastestLapTime: '1.33.761', podium1: 'Evil Tactician', podium2: 'hxrry27', podium3: 'Kyuubi0kid', poleDriver: 'Evil Tactician', poleTime: '1.32.102' },
      'austin': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.37.198', podium1: 'hxrry27', podium2: 'Evil Tactician', podium3: 'Verstappen', poleDriver: 'hxrry27', poleTime: '1.35.347' },
      'mexico': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.19.078', podium1: 'Evil Tactician', podium2: 'hxrry27', podium3: 'Kyuubi0kid', poleDriver: 'Evil Tactician', poleTime: '1.17.240' },
      'interlagos': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.10.592', podium1: 'hxrry27', podium2: 'Evil Tactician', podium3: 'Kyuubi0kid', poleDriver: 'Evil Tactician', poleTime: '1.08.896' },
      'yas-marina': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.39.385', podium1: 'hxrry27', podium2: 'Kol_ri', podium3: 'MagicallyMichael', poleDriver: 'hxrry27', poleTime: '1.38.159' },
      'portimao': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.20.588', podium1: 'hxrry27', podium2: 'Evil Tactician', podium3: 'Kyuubi0kid', poleDriver: 'Evil Tactician', poleTime: '1.19.102' },
      'paul-ricard': { fastestLapDriver: 'Kol_ri', fastestLapTime: '1.34.324', podium1: 'Evil Tactician', podium2: 'Kyuubi0kid', podium3: 'Kol_ri', poleDriver: 'Kol_ri', poleTime: '1.32.118' },
      'shanghai': { fastestLapDriver: 'MagicallyMichael', fastestLapTime: '1.38.338', podium1: 'hxrry27', podium2: 'Verstappen', podium3: 'Perez', poleDriver: 'MagicallyMichael', poleTime: '1.34.820' },
      'russia': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.36.284', podium1: 'Evil Tactician', podium2: 'hxrry27', podium3: 'Kyuubi0kid', poleDriver: 'Kyuubi0kid', poleTime: '1.33.917' }
    },
    standings: {
      drivers: [
        { position: 'P1', driver: 'hxrry27', points: 442, team: 'Alfa Romeo' },
        { position: 'P2', driver: 'Evil Tactician', points: 416, team: 'McLaren' },
        { position: 'P3', driver: 'MagicallyMichael', points: 246, team: 'Alfa Romeo' },
        { position: 'P4', driver: 'Kol_ri', points: 219, team: 'Alpine' },
        { position: 'P5', driver: 'Verstappen', points: 204, team: 'Red Bull' },
        { position: 'P6', driver: 'Kyuubi0kid', points: 175, team: 'McLaren' },
        { position: 'P7', driver: 'Leclerc', points: 101, team: 'Ferrari' },
        { position: 'P8', driver: 'Tsunoda', points: 98, team: 'Alpha Tauri' },
        { position: 'P9', driver: 'Sainz', points: 96, team: 'Ferrari' },
        { position: 'P10', driver: 'Vettel', points: 82, team: 'Aston Martin' },
        { position: 'P11', driver: 'Gasly', points: 78, team: 'Alpha Tauri' },
        { position: 'P12', driver: 'Jober', points: 53, team: 'Mercedes' },
        { position: 'P13', driver: 'Perez', points: 51, team: 'Red Bull' },
        { position: 'P14', driver: 'Ocon', points: 47, team: 'Alpine' },
        { position: 'P15', driver: 'Stroll', points: 19, team: 'Aston Martin' },
        { position: 'P16', driver: 'Latifi', points: 15, team: 'Williams' },
        { position: 'P17', driver: 'Spacey', points: 11, team: 'Mercedes' },
        { position: 'P18', driver: 'Russell', points: 7, team: 'Williams' },
        { position: 'P19', driver: 'Schumacher', points: 1, team: 'Haas' },
        { position: 'P20', driver: 'LFFPicard', points: 0, team: 'Haas' }
      ],
      constructors: [
        { position: 'P1', constructor: 'Alfa Romeo', points: 688 },
        { position: 'P2', constructor: 'McLaren', points: 591 },
        { position: 'P3', constructor: 'Alpine', points: 266 },
        { position: 'P4', constructor: 'Red Bull', points: 257 },
        { position: 'P5', constructor: 'Ferrari', points: 199 },
        { position: 'P6', constructor: 'Alpha Tauri', points: 174 },
        { position: 'P7', constructor: 'Aston Martin', points: 101 },
        { position: 'P8', constructor: 'Mercedes', points: 62 },
        { position: 'P9', constructor: 'Williams', points: 22 },
        { position: 'P10', constructor: 'Haas', points: 1 }
      ]
    }
  },
  8: {
    game: 'F1 22',
    dates: 'Aug 23 > Jan 24',
    lineups: {
      'hxrry27': 'Williams',
      'MagicallyMichael': 'Williams',
      'Evil Tactician': 'Alpine',
      'LFFPicard': 'Alpha Tauri',
      'Kol_ri': 'McLaren',
      'Jober': 'Mercedes',
      'Spacey': 'Ferrari',
      'SeerUK': 'Alpha Tauri/Haas',
      'Kyuubi0kid': 'Ferrari',
      'Kesla': 'Red Bull',
      'Perez': 'Red Bull',
      'Verstappen': 'Red Bull',
      'Hamilton': 'Mercedes',
      'Sainz': 'Ferrari',
      'Tsunoda': 'Alpha Tauri',
      'Alonso': 'Alpine',
      'Leclerc': 'Ferrari',
      'Vettel': 'Aston Martin',
      'Bottas': 'Alfa Romeo',
      'Norris': 'McLaren',
      'Russell': 'Mercedes',
      'Magnussen': 'Haas',
      'Stroll': 'Aston Martin',
      'Schumacher': 'Haas',
      'Zhou': 'Alfa Romeo',
      'Ocon': 'Alpine',
      'Gasly': 'Alpha Tauri',
      'Albon': 'Williams',
      'Ricciardo': 'McLaren'
    },
    races: {
      'bahrain': { fastestLapDriver: 'Kyuubi0kid', fastestLapTime: '1.32.601', podium1: 'LFFPicard', podium2: 'Evil Tactician', podium3: 'MagicallyMichael', poleDriver: null, poleTime: null },
      'jeddah': { fastestLapDriver: 'LFFPicard', fastestLapTime: '1.33.679', podium1: 'hxrry27', podium2: 'MagicallyMichael', podium3: 'LFFPicard', poleDriver: null, poleTime: null },
      'melbourne': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.23.228', podium1: 'MagicallyMichael', podium2: 'hxrry27', podium3: 'LFFPicard', poleDriver: null, poleTime: null },
      'imola': { fastestLapDriver: 'LFFPicard', fastestLapTime: '1.19.781', podium1: 'Verstappen', podium2: 'hxrry27', podium3: 'Kol_ri', poleDriver: null, poleTime: null },
      'miami': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.41.017', podium1: 'Evil Tactician', podium2: 'Perez', podium3: 'Leclerc', poleDriver: null, poleTime: null },
      'barcelona': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.21.755', podium1: 'MagicallyMichael', podium2: 'Kol_ri', podium3: 'hxrry27', poleDriver: null, poleTime: null },
      'monaco': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.14.850', podium1: 'hxrry27', podium2: 'Zhou', podium3: 'Perez', poleDriver: null, poleTime: null },
      'baku': { fastestLapDriver: 'LFFPicard', fastestLapTime: '1.45.856', podium1: 'hxrry27', podium2: 'Vettel', podium3: 'Evil Tactician', poleDriver: null, poleTime: null },
      'montreal': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.14.191', podium1: 'SeerUK', podium2: 'Perez', podium3: 'Alonso', poleDriver: null, poleTime: null },
      'silverstone': { fastestLapDriver: 'LFFPicard', fastestLapTime: '1.32.457', podium1: 'hxrry27', podium2: 'MagicallyMichael', podium3: 'Kyuubi0kid', poleDriver: null, poleTime: null },
      'spielberg': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.08.954', podium1: 'hxrry27', podium2: 'Verstappen', podium3: 'Alonso', poleDriver: null, poleTime: null },
      'paul-ricard': { fastestLapDriver: 'SeerUK', fastestLapTime: '1.34.420', podium1: 'hxrry27', podium2: 'LFFPicard', podium3: 'SeerUK', poleDriver: null, poleTime: null },
      'hungaroring': { fastestLapDriver: 'Kol_ri', fastestLapTime: '1.22.810', podium1: 'Leclerc', podium2: 'hxrry27', podium3: 'SeerUK', poleDriver: null, poleTime: null },
      'spa-francorchamps': { fastestLapDriver: 'Kol_ri', fastestLapTime: '1.49.522', podium1: 'hxrry27', podium2: 'Kol_ri', podium3: 'Evil Tactician', poleDriver: null, poleTime: null },
      'zandvoort': { fastestLapDriver: 'SeerUK', fastestLapTime: '1.14.148', podium1: 'SeerUK', podium2: 'Perez', podium3: 'Leclerc', poleDriver: null, poleTime: null },
      'monza': { fastestLapDriver: 'SeerUK', fastestLapTime: '1.23.589', podium1: 'SeerUK', podium2: 'hxrry27', podium3: 'LFFPicard', poleDriver: null, poleTime: null },
      'singapore': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.44.463', podium1: 'MagicallyMichael', podium2: 'hxrry27', podium3: 'Sainz', poleDriver: null, poleTime: null },
      'suzuka': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.33.988', podium1: 'hxrry27', podium2: 'Kol_ri', podium3: 'Evil Tactician', poleDriver: null, poleTime: null },
      'austin': { fastestLapDriver: 'Norris', fastestLapTime: '1.41.000', podium1: 'Perez', podium2: 'Vettel', podium3: 'Hamilton', poleDriver: null, poleTime: null },
      'mexico': { fastestLapDriver: 'SeerUK', fastestLapTime: '1.20.229', podium1: 'SeerUK', podium2: 'hxrry27', podium3: 'LFFPicard', poleDriver: null, poleTime: null },
      'interlagos': { fastestLapDriver: 'LFFPicard', fastestLapTime: '1.11.145', podium1: 'SeerUK', podium2: 'Evil Tactician', podium3: 'Sainz', poleDriver: null, poleTime: null },
      'yas-marina': { fastestLapDriver: 'MagicallyMichael', fastestLapTime: '1.28.508', podium1: 'Hamilton', podium2: 'Jober', podium3: 'hxrry27', poleDriver: null, poleTime: null },
      'portimao': { fastestLapDriver: 'MagicallyMichael', fastestLapTime: '1.21.307', podium1: 'hxrry27', podium2: 'Kol_ri', podium3: 'Evil Tactician', poleDriver: null, poleTime: null },
      'shanghai': { fastestLapDriver: 'LFFPicard', fastestLapTime: '1.37.616', podium1: 'MagicallyMichael', podium2: 'hxrry27', podium3: 'LFFPicard', poleDriver: null, poleTime: null },
    },
    standings: {
      drivers: [
        { position: 'P1', driver: 'hxrry27', points: 417, team: 'Williams' },
        { position: 'P2', driver: 'MagicallyMichael', points: 238, team: 'Williams' },
        { position: 'P3', driver: 'SeerUK', points: 177, team: 'Haas' },
        { position: 'P4', driver: 'Evil Tactician', points: 169, team: 'Alpine' },
        { position: 'P5', driver: 'LFFPicard', points: 157, team: 'Alpha Tauri' },
        { position: 'P6', driver: 'Perez', points: 150, team: 'Red Bull' },
        { position: 'P7', driver: 'Verstappen', points: 139, team: 'Red Bull' },
        { position: 'P8', driver: 'Kol_ri', points: 138, team: 'McLaren' },
        { position: 'P9', driver: 'Hamilton', points: 110, team: 'Mercedes' },
        { position: 'P10', driver: 'Sainz', points: 92, team: 'Ferrari' },
        { position: 'P11', driver: 'Jober', points: 85, team: 'Mercedes' },
        { position: 'P12', driver: 'Tsunoda', points: 77, team: 'Alpha Tauri' },
        { position: 'P13', driver: 'Alonso', points: 76, team: 'Alpine' },
        { position: 'P14', driver: 'Leclerc', points: 70, team: 'Ferrari' },
        { position: 'P15', driver: 'Vettel', points: 50, team: 'Aston Martin' },
        { position: 'P16', driver: 'Bottas', points: 46, team: 'Alfa Romeo' },
        { position: 'P17', driver: 'Norris', points: 44, team: 'McLaren' },
        { position: 'P18', driver: 'Russell', points: 40, team: 'Mercedes' },
        { position: 'P19', driver: 'Magnussen', points: 28, team: 'Haas' },
        { position: 'P20', driver: 'Kyuubi0kid', points: 27, team: 'Ferrari' },
        { position: 'P21', driver: 'Stroll', points: 24, team: 'Aston Martin' },
        { position: 'P22', driver: 'Spacey', points: 24, team: 'Ferrari' },
        { position: 'P23', driver: 'Schumacher', points: 20, team: 'Haas' },
        { position: 'P24', driver: 'Zhou', points: 18, team: 'Alfa Romeo' },
        { position: 'P25', driver: 'Ocon', points: 13, team: 'Alpine' },
        { position: 'P26', driver: 'Gasly', points: 10, team: 'Alpha Tauri' },
        { position: 'P27', driver: 'Albon', points: 6, team: 'Williams' },
        { position: 'P28', driver: 'Kesla', points: 0, team: 'Red Bull' },
        { position: 'P29', driver: 'Ricciardo', points: 0, team: 'McLaren' }
      ],
      constructors: [
        { position: 'P1', constructor: 'Williams', points: 671 },
        { position: 'P2', constructor: 'Alpha Tauri', points: 343 },
        { position: 'P3', constructor: 'Red Bull', points: 296 },
        { position: 'P4', constructor: 'Alpine', points: 260 },
        { position: 'P5', constructor: 'Mercedes', points: 244 },
        { position: 'P6', constructor: 'Ferrari', points: 191 },
        { position: 'P7', constructor: 'McLaren', points: 184 },
        { position: 'P8', constructor: 'Haas', points: 105 },
        { position: 'P9', constructor: 'Aston Martin', points: 81 },
        { position: 'P10', constructor: 'Alfa Romeo', points: 69 }
      ]
    }
  },
  9: {
    game: 'F1 23',
    dates: 'Feb 24 > Sep 24',
    lineups: {
      'hxrry27': 'Williams',
      'MagicallyMichael': 'Alpha Tauri/Haas',
      'Evil Tactician': 'Aston Martin/McLaren',
      'LFFPicard': 'Alpine/Aston Martin',
      'Kol_ri': 'Alpine/Aston Martin',
      'Jober': 'McLaren/Mercedes',
      'Spacey': 'Mercedes/Ferrari',
      'SeerUK': 'Williams',
      'Xerxes': 'McLaren/Mercedes',
      'Totsuka': 'Aston Martin/McLaren',
      'Kyuubi0kid': 'Mercedes',
      'Verstappen': 'Red Bull',
      'Leclerc': 'Ferrari',
      'Sainz': 'Ferrari',
      'Russell': 'Mercedes',
      'Piastri': 'McLaren',
      'Alonso': 'Aston Martin',
      'Bottas': 'Alfa Romeo',
      'Ocon': 'Alpine',
      'Tsunoda': 'Alpha Tauri',
      'Hamilton': 'Mercedes',
      'Hulkenberg': 'Haas',
      'Gasly': 'Alpine',
      'Sargeant': 'Williams',
      'Zhou': 'Alfa Romeo',
      'Magnussen': 'Haas',
      'Stroll': 'Aston Martin',
      'Ricciardo': 'Alpha Tauri'
    },
    races: {
      'bahrain': { fastestLapDriver: 'SeerUK', fastestLapTime: '1.33.739', podium1: 'hxrry27', podium2: 'SeerUK', podium3: 'MagicallyMichael', poleDriver: 'SeerUK', poleTime: '1.31.389' },
      'jeddah': { fastestLapDriver: 'SeerUK', fastestLapTime: '1.30.856', podium1: 'hxrry27', podium2: 'MagicallyMichael', podium3: 'SeerUK', poleDriver: 'SeerUK', poleTime: '1.29.253' },
      'melbourne': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.21.985', podium1: 'hxrry27', podium2: 'SeerUK', podium3: 'MagicallyMichael', poleDriver: 'MagicallyMichael', poleTime: '1.19.400' },
      'baku': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.46.816', podium1: 'hxrry27', podium2: 'SeerUK', podium3: 'MagicallyMichael', poleDriver: 'hxrry27', poleTime: '1.43.972' },
      'miami': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.32.163', podium1: 'hxrry27', podium2: 'SeerUK', podium3: 'MagicallyMichael', poleDriver: 'SeerUK', poleTime: '1.29.441' },
      'imola': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.18.246', podium1: 'hxrry27', podium2: 'SeerUK', podium3: 'MagicallyMichael', poleDriver: 'SeerUK', poleTime: '1.16.383' },
      'monaco': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.13.831', podium1: 'hxrry27', podium2: 'Kol_ri', podium3: 'SeerUK', poleDriver: 'hxrry27', poleTime: '1.12.459' },
      'barcelona': { fastestLapDriver: 'MagicallyMichael', fastestLapTime: '1.16.249', podium1: 'hxrry27', podium2: 'MagicallyMichael', podium3: 'Xerxes', poleDriver: 'hxrry27', poleTime: '1.13.632' },
      'montreal': { fastestLapDriver: 'SeerUK', fastestLapTime: '1.22.467', podium1: 'hxrry27', podium2: 'SeerUK', podium3: 'MagicallyMichael', poleDriver: 'hxrry27', poleTime: '1.12.199' },
      'spielberg': { fastestLapDriver: 'MagicallyMichael', fastestLapTime: '1.08.074', podium1: 'hxrry27', podium2: 'MagicallyMichael', podium3: 'Xerxes', poleDriver: 'hxrry27', poleTime: '1.05.967' },
      'silverstone': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.29.785', podium1: 'SeerUK', podium2: 'hxrry27', podium3: 'MagicallyMichael', poleDriver: 'hxrry27', poleTime: '1.27.564' },
      'hungaroring': { fastestLapDriver: 'SeerUK', fastestLapTime: '1.19.756', podium1: 'SeerUK', podium2: 'MagicallyMichael', podium3: 'hxrry27', poleDriver: 'hxrry27', poleTime: '1.18.408' },
      'spa-francorchamps': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.47.353', podium1: 'hxrry27', podium2: 'Xerxes', podium3: 'MagicallyMichael', poleDriver: 'hxrry27', poleTime: null },
      'zandvoort': { fastestLapDriver: 'SeerUK', fastestLapTime: '1.12.627', podium1: 'SeerUK', podium2: 'hxrry27', podium3: 'Evil Tactician', poleDriver: 'Totsuka', poleTime: '1.10.883' },
      'monza': { fastestLapDriver: 'SeerUK', fastestLapTime: '1.22.056', podium1: 'hxrry27', podium2: 'Xerxes', podium3: 'Kol_ri', poleDriver: 'hxrry27', poleTime: null },
      'singapore': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.36.553', podium1: 'hxrry27', podium2: 'MagicallyMichael', podium3: 'SeerUK', poleDriver: 'hxrry27', poleTime: '1.31.892' },
      'suzuka': { fastestLapDriver: 'MagicallyMichael', fastestLapTime: '1.35.858', podium1: 'Totsuka', podium2: 'hxrry27', podium3: 'MagicallyMichael', poleDriver: 'Xerxes', poleTime: '1.29.444' },
      'losail': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.25.867', podium1: 'MagicallyMichael', podium2: 'Kol_ri', podium3: 'Totsuka', poleDriver: 'hxrry27', poleTime: '1.23.634' },
      'austin': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.37.878', podium1: 'Totsuka', podium2: 'Xerxes', podium3: 'MagicallyMichael', poleDriver: 'hxrry27', poleTime: '1.35.179' },
      'mexico': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.20.861', podium1: 'hxrry27', podium2: 'SeerUK', podium3: 'Totsuka', poleDriver: 'hxrry27', poleTime: '1.18.316' },
      'interlagos': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.12.464', podium1: 'MagicallyMichael', podium2: 'Xerxes', podium3: 'Totsuka', poleDriver: 'Xerxes', poleTime: '1.10.197' },
      'las-vegas': { fastestLapDriver: null, fastestLapTime: null, podium1: 'SeerUK', podium2: 'Evil Tactician', podium3: 'Jober', poleDriver: null, poleTime: null },
      'yas-marina': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.27.007', podium1: 'hxrry27', podium2: 'SeerUK', podium3: 'Xerxes', poleDriver: 'hxrry27', poleTime: null },
      'portimao': { fastestLapDriver: 'Totsuka', fastestLapTime: '1.21.147', podium1: 'Xerxes', podium2: 'MagicallyMichael', podium3: 'Evil Tactician', poleDriver: 'Xerxes', poleTime: '1.18.369' },
      'paul-ricard': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.34.943', podium1: 'hxrry27', podium2: 'Totsuka', podium3: 'MagicallyMichael', poleDriver: 'hxrry27', poleTime: '1.32.048' },
      'shanghai': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.35.692', podium1: 'Xerxes', podium2: 'hxrry27', podium3: 'Evil Tactician', poleDriver: 'Xerxes', poleTime: '1.33.592' },
    },
    standings: {
      drivers: [
        { position: 'P1', driver: 'hxrry27', points: 545, team: 'Williams' },
        { position: 'P2', driver: 'MagicallyMichael', points: 386, team: 'Haas' },
        { position: 'P3', driver: 'SeerUK', points: 329, team: 'Williams' },
        { position: 'P4', driver: 'Xerxes', points: 269, team: 'Mercedes' },
        { position: 'P5', driver: 'Evil Tactician', points: 219, team: 'McLaren' },
        { position: 'P6', driver: 'Totsuka', points: 218, team: 'McLaren' },
        { position: 'P7', driver: 'Kol_ri', points: 168, team: 'Aston Martin' },
        { position: 'P8', driver: 'Jober', points: 137, team: 'Mercedes' },
        { position: 'P9', driver: 'Verstappen', points: 102, team: 'Red Bull' },
        { position: 'P10', driver: 'LFFPicard', points: 82, team: 'Aston Martin' },
        { position: 'P11', driver: 'Perez', points: 45, team: 'Red Bull' },
        { position: 'P12', driver: 'Leclerc', points: 38, team: 'Ferrari' },
        { position: 'P13', driver: 'Sainz', points: 29, team: 'Ferrari' },
        { position: 'P14', driver: 'Russell', points: 12, team: 'Mercedes' },
        { position: 'P15', driver: 'Piastri', points: 10, team: 'McLaren' },
        { position: 'P16', driver: 'Spacey', points: 10, team: 'Ferrari' },
        { position: 'P17', driver: 'Alonso', points: 8, team: 'Aston Martin' },
        { position: 'P18', driver: 'Bottas', points: 7, team: 'Alfa Romeo' },
        { position: 'P19', driver: 'Ocon', points: 7, team: 'Alpine' },
        { position: 'P20', driver: 'Tsunoda', points: 7, team: 'Alpha Tauri' },
        { position: 'P21', driver: 'Hamilton', points: 6, team: 'Mercedes' },
        { position: 'P22', driver: 'Hulkenberg', points: 6, team: 'Haas' },
        { position: 'P23', driver: 'Gasly', points: 4, team: 'Alpine' },
        { position: 'P24', driver: 'Sargeant', points: 4, team: 'Williams' },
        { position: 'P25', driver: 'Zhou', points: 3, team: 'Alfa Romeo' },
        { position: 'P26', driver: 'Magnussen', points: 0, team: 'Haas' },
        { position: 'P27', driver: 'Stroll', points: 0, team: 'Aston Martin' },
        { position: 'P28', driver: 'Ricciardo', points: 0, team: 'Alpha Tauri' },
        { position: 'P29', driver: 'Kyuubi0kid', points: 0, team: 'Mercedes' }
      ],
      constructors: [
        { position: 'P1', constructor: 'Williams', points: 878 },
        { position: 'P2', constructor: 'McLaren', points: 475 },
        { position: 'P3', constructor: 'Mercedes', points: 255 },
        { position: 'P4', constructor: 'Aston Martin', points: 247 },
        { position: 'P5', constructor: 'Alpha Tauri', points: 209 },
        { position: 'P6', constructor: 'Haas', points: 190 },
        { position: 'P7', constructor: 'Alpine', points: 173 },
        { position: 'P8', constructor: 'Red Bull', points: 147 },
        { position: 'P9', constructor: 'Ferrari', points: 67 },
        { position: 'P10', constructor: 'Alfa Romeo', points: 10 }
      ]
    }
  },
  10: {
    game: 'F1 23',
    dates: 'Oct 24 > Feb 25',
    lineups: {
      'hxrry27': 'Williams',
      'Totsuka': 'Aston Martin/Alfa Romeo', 
      'Xerxes': 'Aston Martin',
      'Evil Tactician': 'McLaren',
      'Jober': 'Mercedes',
      'MagicallyMichael': 'Haas/Williams',
      'Kol_ri': 'McLaren/Alpine', 
      'Spacey': 'Ferrari',
      'Verstappen': 'Red Bull',
      'Hamilton': 'Mercedes',
      'Perez': 'Red Bull',
      'Russell': 'Mercedes',
      'Leclerc': 'Ferrari',
      'Sainz': 'Ferrari',
      'Alonso': 'Aston Martin',
      'Tsunoda': 'Alpha Tauri',
      'Gasly': 'Alpine',
      'Ocon': 'Alpine',
      'Norris': 'McLaren',
      'Piastri': 'McLaren',
      'Bottas': 'Alfa Romeo',
      'Ricciardo': 'Alpha Tauri',
      'Albon': 'Williams',
      'Zhou': 'Alfa Romeo',
      'Magnussen': 'Haas',
      'Hulkenberg': 'Haas',
      'Stroll': 'Aston Martin',
      'Sargeant': 'Williams',
      'SeerUK': 'Williams'
    },
    races: {

      'bahrain': { fastestLapDriver: 'MagicallyMichael', fastestLapTime: '1.33.403', podium1: 'hxrry27', podium2: 'Totsuka', podium3: 'Xerxes', poleDriver: 'SeerUK', poleTime: '1.31.034' },
      'jeddah': { fastestLapDriver: 'Kol_ri', fastestLapTime: '1.32.065', podium1: 'Totsuka', podium2: 'hxrry27', podium3: 'Kol_ri', poleDriver: 'hxrry27', poleTime: null },
      'melbourne': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.20.825', podium1: 'MagicallyMichael', podium2: 'hxrry27', podium3: 'Kol_ri', poleDriver: 'hxrry27', poleTime: '1.19.205' },
      'baku': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.46.309', podium1: 'hxrry27', podium2: 'Verstappen', podium3: 'Leclerc', poleDriver: 'Xerxes', poleTime: '1.44.277' },
      'miami': { fastestLapDriver: 'MagicallyMichael', fastestLapTime: '1.32.419', podium1: 'Totsuka', podium2: 'Evil Tactician', podium3: 'Jober', poleDriver: 'Evil Tactician', poleTime: '1.29.416' },
      'imola': { fastestLapDriver: 'Totsuka', fastestLapTime: '1.18.172', podium1: 'Totsuka', podium2: 'hxrry27', podium3: 'Evil Tactician', poleDriver: 'Totsuka', poleTime: '1.16.314' },
      'monaco': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.13.982', podium1: 'hxrry27', podium2: 'Hamilton', podium3: 'Jober', poleDriver: 'Totsuka', poleTime: '1.12.459' },
      'barcelona': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.15.189', podium1: 'hxrry27', podium2: 'Totsuka', podium3: 'Kol_ri', poleDriver: 'hxrry27', poleTime: '1.13.608' },
      'montreal': { fastestLapDriver: 'Totsuka', fastestLapTime: '1.13.093', podium1: 'Totsuka', podium2: 'MagicallyMichael', podium3: 'Evil Tactician', poleDriver: 'Totsuka', poleTime: null },
      'spielberg': { fastestLapDriver: 'Kol_ri', fastestLapTime: '1.07.433', podium1: 'MagicallyMichael', podium2: 'hxrry27', podium3: 'Evil Tactician', poleDriver: 'MagicallyMichael', poleTime: '1.05.643' },
      'silverstone': { fastestLapDriver: 'Totsuka', fastestLapTime: '1.30.519', podium1: 'Totsuka', podium2: 'hxrry27', podium3: 'MagicallyMichael', poleDriver: 'Totsuka', poleTime: '1.27.717' },
      'hungaroring': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.19.543', podium1: 'hxrry27', podium2: 'Evil Tactician', podium3: 'Xerxes', poleDriver: 'Totsuka', poleTime: '1.17.822' },
      'spa-francorchamps': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.46.566', podium1: 'Totsuka', podium2: 'Xerxes', podium3: 'hxrry27', poleDriver: 'Xerxes', poleTime: '1.44.194' },
      'zandvoort': { fastestLapDriver: 'MagicallyMichael', fastestLapTime: '1.13.284', podium1: 'MagicallyMichael', podium2: 'Evil Tactician', podium3: 'Totsuka', poleDriver: 'hxrry27', poleTime: '1.10.825' },
      'monza': { fastestLapDriver: 'MagicallyMichael', fastestLapTime: '1.22.309', podium1: 'hxrry27', podium2: 'Xerxes', podium3: 'Totsuka', poleDriver: 'hxrry27', poleTime: '1.20.734' },
      'singapore': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.34.072', podium1: 'hxrry27', podium2: 'Evil Tactician', podium3: 'Xerxes', poleDriver: 'Xerxes', poleTime: '1.32.125' },
      'suzuka': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.31.333', podium1: 'hxrry27', podium2: 'MagicallyMichael', podium3: 'Xerxes', poleDriver: 'Evil Tactician', poleTime: '1.29.287' },
      'losail': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.26.075', podium1: 'Xerxes', podium2: 'Totsuka', podium3: 'hxrry27', poleDriver: 'Xerxes', poleTime: '1.23.096' },
      'mexico': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.20.149', podium1: 'MagicallyMichael', podium2: 'Totsuka', podium3: 'hxrry27', poleDriver: 'Totsuka', poleTime: '1.18.524' },
      'interlagos': { fastestLapDriver: 'Xerxes', fastestLapTime: '1.12.122', podium1: 'hxrry27', podium2: 'Totsuka', podium3: 'Evil Tactician', poleDriver: 'Totsuka', poleTime: '1.09.727' },
      'las-vegas': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.36.472', podium1: 'hxrry27', podium2: 'MagicallyMichael', podium3: 'Xerxes', poleDriver: 'Evil Tactician', poleTime: '1.34.020' },
      'yas-marina': { fastestLapDriver: 'hxrry27', fastestLapTime: '1.26.440', podium1: 'Xerxes', podium2: 'hxrry27', podium3: 'Totsuka', poleDriver: 'hxrry27', poleTime: '1.24.506' },
      'portimao': { fastestLapDriver: 'Totsuka', fastestLapTime: '1.21.283', podium1: 'Xerxes', podium2: 'Evil Tactician', podium3: 'MagicallyMichael', poleDriver: 'Xerxes', poleTime: '1.18.109' },
      'paul-ricard': { fastestLapDriver: 'Xerxes', fastestLapTime: '1.34.112', podium1: 'Xerxes', podium2: 'Evil Tactician', podium3: 'MagicallyMichael', poleDriver: 'Evil Tactician', poleTime: '1.39.567' },
      'shanghai': { fastestLapDriver: 'Evil Tactician', fastestLapTime: '1.36.018', podium1: 'Evil Tactician', podium2: 'Xerxes', podium3: 'MagicallyMichael', poleDriver: 'Evil Tactician', poleTime: '1.33.512' },
      'austin': { fastestLapDriver: 'Totsuka', fastestLapTime: '1.37.680', podium1: 'Evil Tactician', podium2: 'Xerxes', podium3: 'MagicallyMichael', poleDriver: 'Evil Tactician', poleTime: '1.34.980' }
    },
    standings: { 
      drivers: [ 
        { position: 'P1', driver: 'hxrry27', points: 472, team: 'Williams' }, 
        { position: 'P2', driver: 'Totsuka', points: 392, team: 'Alfa Romeo' }, 
        { position: 'P3', driver: 'Xerxes', points: 358, team: 'Aston Martin' }, 
        { position: 'P4', driver: 'MagicallyMichael', points: 345, team: 'Williams' }, 
        { position: 'P5', driver: 'Evil Tactician', points: 335, team: 'McLaren' }, 
        { position: 'P6', driver: 'Verstappen', points: 126, team: 'Red Bull' }, 
        { position: 'P7', driver: 'Kol_ri', points: 114, team: 'Alpine' }, 
        { position: 'P8', driver: 'Hamilton', points: 93, team: 'Mercedes' }, 
        { position: 'P9', driver: 'Perez', points: 93, team: 'Red Bull' }, 
        { position: 'P10', driver: 'Jober', points: 74, team: 'Mercedes' }, 
        { position: 'P11', driver: 'Russell', points: 72, team: 'Mercedes' }, 
        { position: 'P12', driver: 'Leclerc', points: 68, team: 'Ferrari' }, 
        { position: 'P13', driver: 'Sainz', points: 39, team: 'Ferrari' }, 
        { position: 'P14', driver: 'Alonso', points: 21, team: 'Aston Martin' }, 
        { position: 'P15', driver: 'Tsunoda', points: 11, team: 'Alpha Tauri' }, 
        { position: 'P16', driver: 'Gasly', points: 10, team: 'Alpine' }, 
        { position: 'P17', driver: 'Ocon', points: 9, team: 'Alpine' }, 
        { position: 'P18', driver: 'Norris', points: 7, team: 'McLaren' }, 
        { position: 'P19', driver: 'Piastri', points: 4, team: 'McLaren' }, 
        { position: 'P20', driver: 'Bottas', points: 3, team: 'Alfa Romeo' }, 
        { position: 'P21', driver: 'Ricciardo', points: 2, team: 'Alpha Tauri' }, 
        { position: 'P22', driver: 'Albon', points: 2, team: 'Williams' },
        { position: 'P23', driver: 'Zhou', points: 0, team: 'Alfa Romeo' },
        { position: 'P24', driver: 'Magnussen', points: 0, team: 'Haas' },
        { position: 'P25', driver: 'Hulkenberg', points: 0, team: 'Haas' },
        { position: 'P26', driver: 'Stroll', points: 0, team: 'Aston Martin' },
        { position: 'P27', driver: 'Sargeant', points: 0, team: 'Williams' },
        { position: 'P28', driver: 'Spacey', points: 0, team: 'Ferrari' },
        { position: 'P29', driver: 'SeerUK', points: 0, team: 'Williams' }
      ], 
      constructors: [
        { position: 'P1', constructor: 'Williams', points: 808 },
        { position: 'P2', constructor: 'Aston Martin', points: 612 }, 
        { position: 'P3', constructor: 'McLaren', points: 460 }, 
        { position: 'P4', constructor: 'Mercedes', points: 239 }, 
        { position: 'P5', constructor: 'Red Bull', points: 219 }, 
        { position: 'P6', constructor: 'Alfa Romeo', points: 162 }, 
        { position: 'P7', constructor: 'Ferrari', points: 107 }, 
        { position: 'P8', constructor: 'Alpine', points: 19 }, 
        { position: 'P9', constructor: 'Alpha Tauri', points: 13 }, 
        { position: 'P10', constructor: 'Haas', points: 11 } 
      ] 
    }
  }
}